import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.backend.Database;

import javax.swing.*;
import java.awt.*;

public class LoginPanel {
    private JPanel loginpanel;
    private JTextField textField1;
    private JPasswordField passwordField1;
    private JButton zalogujButton;
    private JButton zarejestrujButton;

    public static void main(String[] args) {
        JFrame frame = new JFrame("Ekran logowania do aplikacji");


        frame.setContentPane(new LoginPanel().loginpanel);
        frame.setPreferredSize(new Dimension(800, 600));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    LoginPanel() {
        zalogujButton.addActionListener(e -> {

            try {


                String username = this.textField1.getText();

                String password = new String(this.passwordField1.getPassword());

                if (username.equals("") || password.equals("")) {
                    JOptionPane.showMessageDialog(this.loginpanel, "Wprowadź login i hasło", "Brak danych wejściowych", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (Database.authenticateUser(username, password)) {

                    JFrame frame = new JFrame("Aplikacja do sprawdzania kursów polskiej waluty");
                    frame.setContentPane(new MainPanel().$$$getRootComponent$$$());
                    frame.setPreferredSize(new Dimension(800, 600));
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    frame.pack();
                    frame.setVisible(true);
                    SwingUtilities.getWindowAncestor(loginpanel).dispose();

                } else {
                    JOptionPane.showMessageDialog(this.loginpanel, "Brak podanego użytkownika w bazie", "Błąd identyfikacji", JOptionPane.ERROR_MESSAGE);
                }


            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(this.loginpanel, "Wprowadź login i hasło", "Brak danych wejściowych", JOptionPane.ERROR_MESSAGE);
            }


        });

        zarejestrujButton.addActionListener(e -> {

            JFrame frame = new JFrame("Ekran rejestracji użytkownika");
            frame.setContentPane(new RegisterPanel().$$$getRootComponent$$$());
            frame.setPreferredSize(new Dimension(800, 600));
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.pack();
            frame.setVisible(true);
            SwingUtilities.getWindowAncestor(loginpanel).dispose();

        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loginpanel = new JPanel();
        loginpanel.setLayout(new GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
        loginpanel.setBackground(new Color(-1));
        textField1 = new JTextField();
        textField1.setHorizontalAlignment(0);
        loginpanel.add(textField1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        passwordField1 = new JPasswordField();
        passwordField1.setHorizontalAlignment(0);
        loginpanel.add(passwordField1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-16777216));
        label1.setForeground(new Color(-16777216));
        label1.setText("Wprowadź nazwę użytkownika:");
        loginpanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setBackground(new Color(-16777216));
        label2.setForeground(new Color(-16777216));
        label2.setText("Wprowadź hasło:");
        loginpanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zalogujButton = new JButton();
        zalogujButton.setText("Zaloguj");
        loginpanel.add(zalogujButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        zarejestrujButton = new JButton();
        zarejestrujButton.setText("Zarejestruj");
        loginpanel.add(zarejestrujButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginpanel;
    }

}
